# Generated by Django 3.2.4 on 2021-07-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('telf', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Acount Manager',
                'verbose_name_plural': 'Acount Managers',
            },
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'state',
                'verbose_name_plural': 'states',
            },
        ),
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=30)),
                ('Fprestamo', models.DateTimeField()),
                ('Fentrega', models.DateTimeField()),
                ('guia', models.ImageField(upload_to='guias')),
                ('AM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestamos.am')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestamos.client')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestamos.estado')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestamos.partner')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
