# Generated by Django 3.2.4 on 2021-08-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0002_alter_devices_guia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='guia',
            field=models.ImageField(upload_to='guias'),
        ),
    ]
