# Generated by Django 3.2.4 on 2021-08-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0004_auto_20210806_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='identificador',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='devices',
            name='serial_number',
            field=models.CharField(max_length=50),
        ),
    ]
