# Generated by Django 3.2.4 on 2021-08-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0006_alter_devices_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='guia',
            field=models.ImageField(blank=True, null=True, upload_to='guias'),
        ),
    ]
