# Generated by Django 3.2.4 on 2021-08-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0007_alter_devices_guia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='devices',
            name='partner',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='partner',
        ),
    ]
