# Generated by Django 3.2.4 on 2021-08-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0008_auto_20210813_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='codigo_prestamo',
            field=models.IntegerField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
