# Generated by Django 3.2.4 on 2021-08-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0009_devices_codigo_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='codigo_prestamo',
            field=models.IntegerField(),
        ),
    ]
