# Generated by Django 3.2.4 on 2021-08-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0010_alter_devices_codigo_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='guia',
            field=models.ImageField(blank=True, null=True, upload_to='guias_salida'),
        ),
    ]
