# Generated by Django 3.2.4 on 2021-08-18 16:46

import Prestamos.cambiar_nombre_prestamo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0011_alter_devices_guia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='guia',
            field=models.ImageField(blank=True, null=True, upload_to=Prestamos.cambiar_nombre_prestamo.path_and_rename),
        ),
    ]
