# Generated by Django 3.2.4 on 2021-08-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0013_devices_correo_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='responsable',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
