# Generated by Django 3.2.4 on 2021-08-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0014_devices_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='guia',
        ),
    ]
