# Generated by Django 3.2.4 on 2021-07-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'sector',
                'verbose_name_plural': 'sectores',
            },
        ),
    ]
