# Generated by Django 3.2.4 on 2021-08-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices_Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('AM', models.CharField(max_length=50)),
                ('partner', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=25)),
                ('cliente', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=30)),
                ('correo_contacto', models.EmailField(max_length=40)),
                ('Fprestamo', models.DateTimeField()),
                ('Fentregado', models.DateTimeField()),
                ('codigo_prestamo', models.IntegerField()),
                ('guia_devolucion', models.ImageField(blank=True, null=True, upload_to='guias_entrada')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
