# Generated by Django 3.2.4 on 2021-08-27 15:18

import Prestamos.cambiar_nombre_prestamo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historial_Costa_Rica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices_historial',
            name='guia_devolucion',
            field=models.ImageField(blank=True, null=True, upload_to=Prestamos.cambiar_nombre_prestamo.path_and_rename_CR),
        ),
    ]
