# Generated by Django 3.2.4 on 2021-08-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos_Costa_Rica', '0002_remove_devices_guia'),
        ('Historial_Costa_Rica', '0002_alter_devices_historial_guia_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices_historial',
            name='AM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestamos_Costa_Rica.am'),
        ),
    ]
