# Generated by Django 3.2.4 on 2021-08-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Historial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telf', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Acount Manager',
                'verbose_name_plural': 'Acount Managers',
            },
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
            },
        ),
        migrations.AlterField(
            model_name='devices_historial',
            name='AM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historial.am'),
        ),
        migrations.AlterField(
            model_name='devices_historial',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historial.client'),
        ),
        migrations.AlterField(
            model_name='devices_historial',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Historial.partner'),
        ),
    ]
