# Generated by Django 3.2.4 on 2021-08-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historial', '0002_auto_20210809_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices_historial',
            name='AM',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='devices_historial',
            name='cliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='devices_historial',
            name='partner',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='AM',
        ),
        migrations.DeleteModel(
            name='client',
        ),
        migrations.DeleteModel(
            name='partner',
        ),
    ]
