# Generated by Django 3.2.4 on 2021-08-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historial', '0005_devices_historial_guia_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices_historial',
            name='guia_devolucion',
            field=models.ImageField(upload_to='guias_entrada'),
        ),
    ]
