# Generated by Django 3.2.4 on 2021-08-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historial', '0008_remove_devices_historial_guia_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices_historial',
            name='guia_devolucion',
            field=models.ImageField(blank=True, null=True, upload_to='guias_entrada'),
        ),
    ]
