# Generated by Django 3.2.4 on 2021-08-27 15:18

import Prestamos.cambiar_nombre_prestamo
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0015_remove_devices_guia'),
        ('Historial', '0010_auto_20210825_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices_historial',
            name='AM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestamos.am'),
        ),
        migrations.AlterField(
            model_name='devices_historial',
            name='guia_devolucion',
            field=models.ImageField(blank=True, null=True, upload_to=Prestamos.cambiar_nombre_prestamo.path_and_rename),
        ),
    ]
